var menudata={children:[
{text:"Титульная страница",url:"index.html"},
{text:"Классы",url:"annotated.html",children:[
{text:"Классы",url:"annotated.html"},
{text:"Алфавитный указатель классов",url:"classes.html"},
{text:"Иерархия классов",url:"inherits.html"},
{text:"Члены классов",url:"functions.html",children:[
{text:"Указатель",url:"functions.html",children:[
{text:"d",url:"functions.html#index_d"},
{text:"e",url:"functions.html#index_e"},
{text:"f",url:"functions.html#index_f"},
{text:"g",url:"functions.html#index_g"},
{text:"m",url:"functions.html#index_m"},
{text:"n",url:"functions.html#index_n"},
{text:"o",url:"functions.html#index_o"},
{text:"p",url:"functions.html#index_p"},
{text:"r",url:"functions.html#index_r"},
{text:"s",url:"functions.html#index_s"}]},
{text:"Функции",url:"functions_func.html",children:[
{text:"d",url:"functions_func.html#index_d"},
{text:"e",url:"functions_func.html#index_e"},
{text:"f",url:"functions_func.html#index_f"},
{text:"g",url:"functions_func.html#index_g"},
{text:"m",url:"functions_func.html#index_m"},
{text:"n",url:"functions_func.html#index_n"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"}]}]}]},
{text:"Файлы",url:"files.html",children:[
{text:"Файлы",url:"files.html"},
{text:"Список членов всех файлов",url:"globals.html",children:[
{text:"Указатель",url:"globals.html",children:[
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"i",url:"globals.html#index_i"},
{text:"j",url:"globals.html#index_j"},
{text:"k",url:"globals.html#index_k"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"n",url:"globals.html#index_n"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"u",url:"globals.html#index_u"}]},
{text:"Функции",url:"globals_func.html"},
{text:"Переменные",url:"globals_vars.html"},
{text:"Макросы",url:"globals_defs.html"}]}]}]}
